### ISSUE TITLE
KubeVS completely breaks loading of kubejs scripts

### ISSUE THREAD

**Issue by AlexanderwithaA** [TechTastic/kubevs#2] opened 2023-11-04 07:36 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

Having architectury api, vs2, kubejs, kubevs, fabric api, and rhino causes all kubejs scripts to fail to load. Disabling kubevs fixes the issue.

### Issue reproduction

Download and run architectury api, vs2, kubejs, kubevs, fabric api, and rhino on a fabric 1.18.2 instance. The example scripts that come with kubejs shouldn't work and neither should any you make.

**Comment by TechTastic** [comment] 2023-11-04 12:09
Provide the logs but I feel this has the same root cause as your other issue, which is VS2's restructure, Id suggest downgrading VS2 for now

**Comment by TechTastic** [comment] 2024-12-26 05:42
Fixed in latest

**Closed as completed by TechTastic** 2024-12-26 05:42 UTC
Labels: bug
